# Generated by Django 5.2.6 on 2025-11-11 15:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Принят', 'Принят'), ('Отменен', 'Отменен'), ('Собирается', 'Собирается'), ('Готов к доставке', 'Готов к доставке'), ('Завершен', 'Завершен'), ('Возвращен', 'Возвращен')], default='В обработке')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=10)),
                ('flat', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'товар заказа',
                'verbose_name_plural': 'товары заказа',
            },
        ),
    ]
